[PSX]
host = 127.0.0.1
port = 10747

[INTERFERENCE]
#percentage grey area where GPS interference is intermittent
transition_band_percent = 10
#keep GPS signal on/off for at least min_seconds
transition_min_seconds  = 5